# Generated by Django 2.2.3 on 2020-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200129_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_name',
            new_name='account',
        ),
    ]
