# Generated by Django 2.2.3 on 2020-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200126_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
